# Generated by Django 6.0.8 on 2026-08-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_bairro_latitude_bairro_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Em andamento'), ('resolvido', 'Resolvido')], default='pendente', max_length=20),
        ),
    ]
